#!/bin/sh

case "$1" in
  start)
    /m/nserver/run_dev_server.js start > /var/log/nserver.log 2> /var/log/nserver.err
    ;;
  stop)
    /m/nserver/run_dev_server.js stop
    ;;
  restart)
    /m/nserver/run_dev_server.js stop
    /m/nserver/run_dev_server.js start > /var/log/nserver.log 2> /var/log/nserver.err
    ;;

  force-reload)
    # No-op
    ;;
  *)
    echo "Usage: nserver {start|stop|restart|force-reload}" >&2
    exit 3
    ;;
esac

:
